Allow profiling examples
    $ cargo profile flamegraph --root example throughput
        Finished dev [unoptimized + debuginfo] target(s) in 0.12s
    Error: faield to create flamegraph

    Caused by:
        0: cargo execution failed
        1: cargo did not produced any useful binary
           "/Users/odin/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo" "build" "--example" "throughput" "--message-format=json"